### ISSUE TITLE
BUG: Conflict with OMZSH Plugin

### ISSUE THREAD

**Issue by Jelloeater** [dex4er/tf#24]
Getting a conflict here https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/terraform
Any ideas on how to fix, while still keeping the original auto complete?

**Comment by dex4er** [comment]
I use this omz plugin and tf too.

You can add

```sh
alias tf='noglob tf'
compdef _terraform tf
```

at the end of `~/.zshrc`
